package com.har.test;

import java.io.Serializable;

import org.hibernate.Session;
import org.hibernate.Transaction;

import com.har.entity.Student;
import com.har.utility.HibernateUtil;

//First Level cache
// By FirstLevelCach is associated with Session
public class GetObjectClientTest {


	public static void main(String[] args) {
		//levelOneCacheTest01();
		//levelOneCacheTest02();
		levelOneCacheTest03();
	 }

	private static void levelOneCacheTest01() {
		Session           session                           = null;
		Student   student                                 = null;		
		
		           //get session object
		            session       = HibernateUtil.getSession();
		     try {
					//get the object
					student = (Student) session.get(Student.class, 5);  //Collects form DB and keeps L1 cache
					System.out.println("#01 :student         :"+student);
					System.out.println("--------------------------------------------------");
					
					Student	student2 = (Student) session.get(Student.class, 5);  //Collects from L1 cache
					System.out.println("#02 :student         :"+student2);
					System.out.println("--------------------------------------------------");
					
					// Remove /evict/clear from L1 Cache
					session.evict(student);     //student is removed from L1 Cache
					
					 //Collects form DB and keeps L1 cache
					Student student3= (Student) session.get(Student.class, 4);  //Collects form DB and keeps L1 cache
					System.out.println("#02 :student         :"+student3);
					System.out.println("--------------------------------------------------");
					
				} catch (Exception e) {
					e.printStackTrace();
				} finally {
					if(session.isOpen()){      //Close Session and SessionFactory
						HibernateUtil.closeSession(session);
						HibernateUtil.closeSessionFactory();
					}
				}
	}
	private static void levelOneCacheTest02() {
		Session           session                           = null;
		Student   student                                 = null;		
		Transaction txn                                     = null;
		
		           //get session object
		            session       = HibernateUtil.getSession();
		     try {
		    	 student     = new Student();
		    	 student.setFirstName("Sujatha");  //#01   //Transient state
		    	 student.setLastName("s");
		    	 student.setMarks(60);
		    	 student.setGrade("B");
		    	 
		    	 //Begin TXN
		    	 txn =session.beginTransaction();
		    	 
		    	 //Save Student object
		    	 Serializable id = session.save(student);  //02       //persistent state   //Here still object state is not  moved to db,but moved to L1 Cache
                 System.out.println("successfully saved student obejct..........."+ id);	 // Id is generated By HB Framework	    	 
		    	 System.out.println();
		    	 
		    	 Student student1=session.get(Student.class, id); //#03      // Here object  is not collect DB,collect from L1 Cache 
		    	 System.out.println("student1 object..........."+ student1);		    	 
		    	 System.out.println();
		    	 
		    	 txn.commit();       //#04 ..Finally  #01 object is moved to DB,
		    	 
				} catch (Exception e) {
					e.printStackTrace();
				} finally {
					if(session.isOpen()){      //Close Session and SessionFactory
						HibernateUtil.closeSession(session);
						HibernateUtil.closeSessionFactory();
					}
				}
	}
		     private static void levelOneCacheTest03() {
		 		Session           session                           = null;
		 		Student   student                                 = null;		
		 		Transaction txn                                     = null;
		 		
		 		           //get session object
		 		            session       = HibernateUtil.getSession();
		 		     try {
		 		
		 		    	 
		 		    	 //Begin TXN
		 		    	 txn =session.beginTransaction();
		 		    	 
		 		    	 //Save Student object
		 		    	student = session.get(Student.class,8);      //persistent state   //Here collect from DB ,keep in L1 Cache
		                  System.out.println("saved student obejct.....is......"+ student);		    	 
		 		    	 System.out.println();
		 		    	 
		 		    	student.setLastName("B");
		 		    	student.setFirstName("Vara lakshmi");
		 		    	
		 		    	//update1
		 		    	session.update(student);
		 		    	
		 		    	student.setMarks(95);
		 		    	student.setGrade("A");
		 		    	
		 		    	//update2
		 		    	session.update(student);

		 		    	 
		 		    	 txn.commit();       
		 		    	 
		 				} catch (Exception e) {
		 					e.printStackTrace();
		 				} finally {
		 					if(session.isOpen()){      //Close Session and SessionFactory
		 						HibernateUtil.closeSession(session);
		 						HibernateUtil.closeSessionFactory();
		 					}
		 				}
		     
	}
	
	
}
